services:
  nexus:
    container_name: nexus
    user: root
    image: sonatype/nexus3:3.83.0
    restart: always
    volumes:
      - ./nexus-data:/nexus-data
  nginx:
    container_name: nginx-server
    image: nginx:1.27-alpine
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nexus-nginx-data:/var/www/html
