---
- name: Ensure blob stores exist
  include_tasks: blobstores.yml
  tags: [configure, blobstores]

- name: Clean repositories marked for deletion
  include_tasks: clean_repositories.yml
  tags: [configure, clean]

# - name: Configure security realms
#   include_tasks: realms.yml
#   tags: [configure, realms]

- name: Configure NPM repositories
  include_tasks: repo_npm.yml
  tags: [configure, npm]

- name: Configure PyPI repositories
  include_tasks: repo_pypi.yml
  tags: [configure, pypi]

- name: Configure Maven repositories
  include_tasks: repo_maven.yml
  tags: [configure, maven]

- name: Configure Docker repositories
  include_tasks: repo_docker.yml
  tags: [configure, docker]

- name: Configure YUM repositories
  include_tasks: repo_yum.yml
  tags: [configure, yum]

- name: Configure raw repositories
  include_tasks: repo_raw.yml
  tags: [configure, raw]
  
- name: Create standard roles
  include_tasks: roles_create.yml
  tags: [configure, roles]

- name: Create users
  include_tasks: users_create.yml
  tags: [configure, users]
