---
- name: Ensure blob stores exist
  ansible.builtin.include_tasks: blobstores.yml
  tags: [configure, blobstores]

- name: Clean repositories marked for deletion
  ansible.builtin.include_tasks: clean_repositories.yml
  tags: [configure, clean]

- name: Configure NPM repositories
  ansible.builtin.include_tasks: repo_npm.yml
  tags: [configure, npm]

- name: Configure PyPI repositories
  ansible.builtin.include_tasks: repo_pypi.yml
  tags: [configure, pypi]

- name: Configure Maven repositories
  ansible.builtin.include_tasks: repo_maven.yml
  tags: [configure, maven]

- name: Configure Docker repositories
  ansible.builtin.include_tasks: repo_docker.yml
  tags: [configure, docker]

- name: Configure YUM repositories
  ansible.builtin.include_tasks: repo_yum.yml
  tags: [configure, yum]

- name: Configure raw repositories
  ansible.builtin.include_tasks: repo_raw.yml
  tags: [configure, raw]

- name: Configure APT repositories
  ansible.builtin.include_tasks: repo_apt.yml
  tags: [configure, apt]

- name: Configure Hugging Face repositories
  ansible.builtin.include_tasks: repo_huggingface.yml
  tags: [configure, huggingface]

- name: Create standard roles
  ansible.builtin.include_tasks: roles_create.yml
  tags: [configure, roles]

- name: Create users
  ansible.builtin.include_tasks: users_create.yml
  tags: [configure, users]
