---
- name: Ensure blob stores exist
  include_tasks: blobstores.yml
  tags: [configure, blobstores]

- name: Clean repositories marked for deletion
  include_tasks: clean_repositories.yml
  tags: [configure, clean]

# - name: Configure security realms
#   include_tasks: realms.yml
#   tags: [configure, realms]

# - name: Create standard roles
#   include_tasks: roles.yml
#   tags: [configure, roles]

# Форматы — каждый со своим тегом
- name: Configure NPM repositories
  include_tasks: repo_npm.yml
  tags: [configure, npm]

- name: Configure PyPI repositories
  include_tasks: repo_pypi.yml
  tags: [configure, pypi]

- name: Configure Maven repositories
  include_tasks: repo_maven.yml
  tags: [configure, maven]
