# Список имён репозиториев, которые нужно создать/удалить
nexus_active_repositories:
  - "npm-proxy"
  - "npm-hosted"
  - "npm-group"
  - "pypi-proxy"
  - "pypi-hosted"
  - "pypi-group"
  - "maven-central"
  - "maven-releases"
  - "maven-snapshots"
  - "maven-public"
  - "xwiki-public"
  - "xwiki-maven"
  - "docker-gh-proxy"
  - "docker-io-proxy"
  - "docker-quay-proxy"
  - "docker-hosted"
  - "docker-hosted-test"
  - "docker-group"
  - "yum-proxy"
  - "ubi-redhat"
  - "yum-hosted"
  - "yum-group"
  - "alpine"
  - "file-share"
  - "apt-hosted"
  - "apt-yandex"
  - "apt-clickhouse"
  - "apt-confluent"
  - "apt-kitware"
  - "apt-llvm"
  - "apt-mariadb"
  - "apt-mongodb"
  - "apt-rabbitmq-server"
  - "apt-rabbitmq-erlang"
  - "apt-toolchain-r"
  - "ansible-galaxy"
  - "huggingface-proxy"

nexus_repositories_to_delete:
  - "nuget.org-proxy"
  - "nuget-hosted"
  - "nuget-group"
