---
nexus_repository_library:
  # --- NPM ---
  npm-proxy:
    name: "npm-proxy"
    format: "npm"
    type: "proxy"
    blob_store: "dev"
    remote_url: "https://registry.npmjs.org/"

  npm-hosted:
    name: "npm-hosted"
    format: "npm"
    type: "hosted"
    blob_store: "dev"

  npm-group:
    name: "npm-group"
    format: "npm"
    type: "group"
    blob_store: "dev"
    member_names:
      - "npm-proxy"
      - "npm-hosted"

  # --- PyPI ---
  pypi-proxy:
    name: "pypi-proxy"
    format: "pypi"
    type: "proxy"
    blob_store: "dev"
    remote_url: "https://pypi.org/simple/"

  pypi-hosted:
    name: "pypi-hosted"
    format: "pypi"
    type: "hosted"
    blob_store: "dev"

  pypi-group:
    name: "pypi-group"
    format: "pypi"
    type: "group"
    blob_store: "dev"
    member_names:
      - "pypi-proxy"
      - "pypi-hosted"

  # --- Maven ---
  maven-central:
    name: "maven-central"
    format: "maven2"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://repo1.maven.org/maven2/"

  maven-releases:
    name: "maven-releases"
    format: "maven2"
    type: "hosted"
    blob_store: "dev"

  maven-snapshots:
    name: "maven-snapshots"
    format: "maven2"
    type: "hosted"
    blob_store: "dev"

  maven-public:
    name: "maven-public"
    format: "maven2"
    type: "group"
    blob_store: "os"
    member_names:
      - "maven-central"
      - "maven-releases"
      - "maven-snapshots"

  # --- Docker ---
  docker-gh-proxy:
    name: "docker-gh-proxy"
    format: "docker"
    type: "proxy"
    blob_store: "docker"
    remote_url: "https://ghcr.io"
    docker_index_type: "REGISTRY"
  
  docker-io-proxy:
    name: "docker-io-proxy"
    format: "docker"
    type: "proxy"
    blob_store: "docker"
    remote_url: "https://registry-1.docker.io"
    docker_index_type: "HUB"
  
  docker-quay-proxy:
    name: "docker-quay-proxy"
    format: "docker"
    type: "proxy"
    blob_store: "docker"
    remote_url: "https://quay.io"
    docker_index_type: "REGISTRY"
  
  docker-hosted:
    name: "docker-hosted"
    format: "docker"
    type: "hosted"
    blob_store: "docker"
    write_policy: "ALLOW"
  
  docker-hosted-test:
    name: "docker-hosted-test"
    format: "docker"
    type: "hosted"
    blob_store: "docker"
    write_policy: "ALLOW"
  
  docker-group:
    name: "docker-group"
    format: "docker"
    type: "group"
    blob_store: "docker"
    member_names:
      - "docker-gh-proxy"
      - "docker-io-proxy"
      - "docker-quay-proxy"
      - "docker-hosted"
      - "docker-hosted-test"
