---
nexus_repository_library:
  # --- NPM ---
  npm-proxy:
    name: "npm-proxy"
    format: "npm"
    type: "proxy"
    blob_store: "dev"
    remote_url: "https://registry.npmjs.org/"

  npm-hosted:
    name: "npm-hosted"
    format: "npm"
    type: "hosted"
    blob_store: "dev"

  npm-group:
    name: "npm-group"
    format: "npm"
    type: "group"
    blob_store: "dev"
    member_names:
      - "npm-proxy"
      - "npm-hosted"

  # --- PyPI ---
  pypi-proxy:
    name: "pypi-proxy"
    format: "pypi"
    type: "proxy"
    blob_store: "dev"
    remote_url: "https://pypi.org/simple/"

  pypi-hosted:
    name: "pypi-hosted"
    format: "pypi"
    type: "hosted"
    blob_store: "dev"

  pypi-group:
    name: "pypi-group"
    format: "pypi"
    type: "group"
    blob_store: "dev"
    member_names:
      - "pypi-proxy"
      - "pypi-hosted"

  # --- Maven ---
  maven-central:
    name: "maven-central"
    format: "maven2"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://repo1.maven.org/maven2/"

  maven-releases:
    name: "maven-releases"
    format: "maven2"
    type: "hosted"
    blob_store: "dev"

  maven-snapshots:
    name: "maven-snapshots"
    format: "maven2"
    type: "hosted"
    blob_store: "dev"

  maven-public:
    name: "maven-public"
    format: "maven2"
    type: "group"
    blob_store: "os"
    member_names:
      - "maven-central"
      - "maven-releases"
      - "maven-snapshots"
