---
nexus_repository_library:
  # --- NPM ---
  npm-proxy:
    name: "npm-proxy"
    format: "npm"
    type: "proxy"
    blob_store: "dev"
    remote_url: "https://registry.npmjs.org/"

  npm-hosted:
    name: "npm-hosted"
    format: "npm"
    type: "hosted"
    blob_store: "dev"

  npm-group:
    name: "npm-group"
    format: "npm"
    type: "group"
    blob_store: "dev"
    member_names:
      - "npm-proxy"
      - "npm-hosted"

  # --- PyPI ---
  pypi-proxy:
    name: "pypi-proxy"
    format: "pypi"
    type: "proxy"
    blob_store: "dev"
    remote_url: "https://pypi.org/simple/"

  pypi-hosted:
    name: "pypi-hosted"
    format: "pypi"
    type: "hosted"
    blob_store: "dev"

  pypi-group:
    name: "pypi-group"
    format: "pypi"
    type: "group"
    blob_store: "dev"
    member_names:
      - "pypi-proxy"
      - "pypi-hosted"

  # --- Maven ---
  maven-central:
    name: "maven-central"
    format: "maven"
    type: "proxy"
    blob_store: "dev"
    remote_url: "https://repo1.maven.org/maven2/"

  maven-releases:
    name: "maven-releases"
    format: "maven"
    type: "hosted"
    blob_store: "dev"

  maven-snapshots:
    name: "maven-snapshots"
    format: "maven"
    type: "hosted"
    blob_store: "dev"

  maven-public:
    name: "maven-public"
    format: "maven"
    type: "group"
    blob_store: "dev"
    member_names:
      - "maven-central"
      - "maven-releases"
      - "maven-snapshots"

  # --- XWiki Maven ---
  xwiki-public:
    name: "xwiki-public"
    format: "maven"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://nexus.xwiki.org/nexus/content/groups/public/"
    maven_layout_policy: "PERMISSIVE"

  xwiki-maven:
    name: "xwiki-maven"
    format: "maven"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://maven.xwiki.org/releases/"
    maven_layout_policy: "STRICT"

  # --- Docker ---
  docker-gh-proxy:
    name: "docker-gh-proxy"
    format: "docker"
    type: "proxy"
    blob_store: "docker"
    remote_url: "https://ghcr.io"
    docker_index_type: "REGISTRY"
  
  docker-io-proxy:
    name: "docker-io-proxy"
    format: "docker"
    type: "proxy"
    blob_store: "docker"
    remote_url: "https://registry-1.docker.io"
    docker_index_type: "HUB"
  
  docker-quay-proxy:
    name: "docker-quay-proxy"
    format: "docker"
    type: "proxy"
    blob_store: "docker"
    remote_url: "https://quay.io"
    docker_index_type: "REGISTRY"
  
  docker-hosted:
    name: "docker-hosted"
    format: "docker"
    type: "hosted"
    blob_store: "docker"
    write_policy: "ALLOW"
  
  docker-hosted-test:
    name: "docker-hosted-test"
    format: "docker"
    type: "hosted"
    blob_store: "docker"
    write_policy: "ALLOW"
  
  docker-group:
    name: "docker-group"
    format: "docker"
    type: "group"
    blob_store: "docker"
    member_names:
      - "docker-gh-proxy"
      - "docker-io-proxy"
      - "docker-quay-proxy"
      - "docker-hosted"
      - "docker-hosted-test"

  # --- YUM ---
  yum-proxy:
    name: "yum-proxy"
    format: "yum"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://mirror.yandex.ru/"
    yum_repodata_depth: 1
  
  ubi-redhat:
    name: "ubi-redhat"
    format: "yum"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://cdn-ubi.redhat.com/"
    yum_repodata_depth: 1
  
  yum-hosted:
    name: "yum-hosted"
    format: "yum"
    type: "hosted"
    blob_store: "os"
    write_policy: "ALLOW"
  
  yum-group:
    name: "yum-group"
    format: "yum"
    type: "group"
    blob_store: "os"
    member_names:
      - "yum-proxy"
      - "ubi-redhat"
      - "yum-hosted"

  # --- RAW ---
  alpine:
    name: "alpine"
    format: "raw"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://mirror.yandex.ru/mirrors/alpine/"

  file-share:
    name: "file-share"
    format: "raw"
    type: "hosted"
    blob_store: "os"
    write_policy: "ALLOW"

  # --- APT ---
  apt-hosted:
    name: "apt-hosted"
    format: "apt"
    type: "hosted"
    blob_store: "dev"
    write_policy: "ALLOW"
    apt_distribution: "jammy"

  # Proxy
  apt-yandex:
    name: "apt-yandex"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://mirror.yandex.ru/"
    apt_distribution: "jammy"

  apt-clickhouse:
    name: "apt-clickhouse"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://packages.clickhouse.com/deb/"
    apt_distribution: "jammy"

  apt-confluent:
    name: "apt-confluent"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://packages.confluent.io/clients/deb/"
    apt_distribution: "jammy"

  apt-kitware:
    name: "apt-kitware"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://apt.kitware.com/ubuntu/"
    apt_distribution: "jammy"

  apt-llvm:
    name: "apt-llvm"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "http://apt.llvm.org/jammy/"
    apt_distribution: "jammy"

  apt-mariadb:
    name: "apt-mariadb"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://mirror.kumi.systems/mariadb/repo/10.11/ubuntu/"
    apt_distribution: "jammy"

  apt-mongodb:
    name: "apt-mongodb"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://repo.mongodb.org/apt/ubuntu/"
    apt_distribution: "jammy"

  apt-rabbitmq-server:
    name: "apt-rabbitmq-server"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://deb1.rabbitmq.com/rabbitmq-server/ubuntu/jammy/"
    apt_distribution: "jammy"

  apt-rabbitmq-erlang:
    name: "apt-rabbitmq-erlang"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://deb1.rabbitmq.com/rabbitmq-erlang/ubuntu/jammy/"
    apt_distribution: "jammy"

  apt-toolchain-r:
    name: "apt-toolchain-r"
    format: "apt"
    type: "proxy"
    blob_store: "os"
    remote_url: "https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu/"
    apt_distribution: "jammy"

  # --- Hugging Face ---
  huggingface-proxy:
    name: "huggingface-proxy"
    format: "huggingface"
    type: "proxy"
    blob_store: "llm"
    remote_url: "https://huggingface.co/"
