nexus_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63643634336664383365313563633464646134376534626561343738313666356536643161653934
          6362306438326636346537643463646330666334346539320a366139643063313864613461376264
          35653937306432366338396264303833353866633861633535623433323466646638363266323934
          3233613730633836650a316262343533316339623430343564353233656331623138333230616133
          65343533666430623762653861323966353764316137373930306630306331303530393331373930
          6662623939363865393131623339656166666235316337623336
